clean up whitespace in install script

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -2,7 +2,7 @@
 
 source $OPENSHIFT_CARTRIDGE_SDK_BASH
 
-case $1 in 
+case $1 in
 	-v|--version)	ver="$2"
 esac
 
@@ -46,10 +46,10 @@ function build_python() {
 	mkdir -p $tdir/python
 	tar xvzf $tdir/tmp.tgz --strip-component=1 -C $tdir/python
 	
-        # if a different version exists, remove it first
-        if [ -d $pdir/usr/bin ]; then
-                rm -rf $pdir/usr
-        fi
+	# if a different version exists, remove it first
+	if [ -d $pdir/usr/bin ]; then
+		rm -rf $pdir/usr
+	fi
 
 	cd $tdir/python
 	./configure --prefix=${pdir}usr/
@@ -62,7 +62,7 @@ function build_python() {
 		$pdir/usr/bin/pip install virtualenv
 	fi
 
-	report_status $? "Installation" 
+	report_status $? "Installation"
 }
 
 function is_virt_installed() {
@@ -73,7 +73,6 @@ function is_virt_installed() {
 }
 
 function create_virt() {
-
 	if [ -f $pdir/usr/bin/virtualenv ]; then
 		$pdir/usr/bin/virtualenv --clear $vdir
 	else
@@ -94,7 +93,7 @@ else
 	client_result "Virtual environment already installed."
 fi
 
-#Clean up temp directory
+# Clean up temp directory
 rm -rf $tdir/python
 rm -f $tdir/tmp.tgz
 
