testing

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -56,8 +56,8 @@ function build_python() {
 	make -j$cpus > /dev/null
 	make install -j$cpus > /dev/null
 
-#	$pdir/usr/bin/python -m ensurepip
-#	$pdir/usr/bin/pip install virtualenv
+	$pdir/usr/bin/python -m ensurepip
+	$pdir/usr/bin/pip install virtualenv
 
 	report_status $? "Installation"
 }
@@ -79,22 +79,22 @@ function create_virt() {
 
 if ! is_python_installed; then
 	build_python
-#	create_virt
+	create_virt
 else
 	client_result "Python $ver already installed."
 fi
 
-#if ! is_virt_installed; then
-#	create_virt
-#else
-#	client_result "Virtual environment already installed."
-#fi
-#
-## Clean up temp directory
-#rm -rf $tdir/python-$ver
-#rm -f $tdir/$ver.tgz
-#
-## pip stores cache in .cache an logs in .pip.
-## Create directories, change ownership and SELinux security context
-#mkdir -p $OPENSHIFT_HOMEDIR/{.cache,.pip}
-#chown $OPENSHIFT_GEAR_UUID.$OPENSHIFT_GEAR_UUID -R $OPENSHIFT_HOMEDIR/.pip $OPENSHIFT_HOMEDIR/.cache
+if ! is_virt_installed; then
+	create_virt
+else
+	client_result "Virtual environment already installed."
+fi
+
+# Clean up temp directory
+rm -rf $tdir/python-$ver
+rm -f $tdir/$ver.tgz
+
+# pip stores cache in .cache an logs in .pip.
+# Create directories, change ownership and SELinux security context
+mkdir -p $OPENSHIFT_HOMEDIR/{.cache,.pip}
+chown $OPENSHIFT_GEAR_UUID.$OPENSHIFT_GEAR_UUID -R $OPENSHIFT_HOMEDIR/.pip $OPENSHIFT_HOMEDIR/.cache
